import { createHash } from "node:crypto";
import { getDb } from "@sushindustries/db/client";
import type { DocumentKind } from "@sushindustries/db/schema";
import {
	and,
	asc,
	desc,
	documents,
	eq,
	referencePages,
	referenceProviders,
	sql,
} from "@sushindustries/db/schema";
import sdl from "../../../../../apollo/schema.graphql?raw";
import {
	getCollection,
	getCollections,
} from "../studio/collections/collections.server";
import {
	getElement,
	getElementShard,
	getElements,
	type ShapedElement,
} from "./elements.server";
import { githubResolvers } from "./github.server";
import type {
	DocumentKind as GraphQlKind,
	Resolvers,
} from "./graphql.generated";

/*
 * The graph, over the projection.
 *
 * Resolvers and nothing else: the schema is `apollo/schema.graphql`, read from
 * disk rather than written twice in a template literal here. One file is the
 * contract, and it is the one Apollo's tooling, the MCP server and this
 * process all read - so there is no version of "the schema" that only one of
 * them has seen.
 *
 * Read-only. Every field's source is a file in git and the way to change one
 * is to change the file, so a mutation here would be a second way to write
 * that the next `sync` would silently discard.
 *
 * `.server.ts` because it opens a database connection. Named for the protocol
 * it speaks, not for the word "graph" - `graph.server.ts` beside it is the
 * JSON-LD entity graph and has nothing to do with this.
 */

/*
 * The connection, per call rather than at module load.
 *
 * `getDb` builds it the first time and remembers it. Calling it inside each
 * resolver rather than destructuring `db` at the top is what keeps a build
 * with no DATABASE_URL from failing at import time: the route is prerendered,
 * the module is loaded, and nothing has asked for a connection yet.
 */
const db = () => getDb();

/**
 * The SDL, inlined at build time from the file Apollo also reads.
 *
 * `?raw` rather than a filesystem read, which is what the assistant's persona
 * and every Markdown page here already do. Reading it at runtime looked
 * simpler and was wrong twice over: the working directory during a build is
 * the app, not the repository, and a schema that has to exist on disk beside
 * the server is a schema the runtime image would have to carry.
 *
 * Inlined, there is still one file. Apollo's tooling, its MCP server and this
 * process all read `apollo/schema.graphql`; this one just reads it earlier.
 */
export function typeDefs(): string {
	return sdl;
}

/*
 * `COMPONENT` on the wire, `component` in the column.
 *
 * Both directions are asserted rather than inferred, and that is the honest
 * shape: `toUpperCase()` returns `string`, so nothing about its result proves
 * it is a member of the enum. The two casts are where that proof stops, and
 * they are safe for one reason worth stating - the enum in the schema is
 * generated by upper-casing this very column's `DocumentKind` union, so the
 * sets cannot disagree without `checkDocumentKindsAgree` failing first.
 *
 * Without the annotation TypeScript widened every document resolver to
 * `kind: string` and refused all fifteen of them against a schema that says
 * `DocumentKind`. The runtime was already right; nothing could say so.
 */
const toKind = (value?: GraphQlKind | null) =>
	value ? (value.toLowerCase() as DocumentKind) : undefined;

const fromKind = (value: DocumentKind) => value.toUpperCase() as GraphQlKind;

const shape = (row: typeof documents.$inferSelect) => ({
	...row,
	kind: fromKind(row.kind),
	syncedAt: row.syncedAt.toISOString(),
});

/** A LIKE pattern that treats the caller's text as text, not as syntax. */
const contains = (value: string) =>
	`%${value.replace(/[\\%_]/g, (char) => `\\${char}`)}%`;

/**
 * Skills, as a view over the documents whose kind is `skill`.
 *
 * Ordered by path and numbered from one on the way out, so the index is a
 * property of the list rather than something stored - which is what keeps it
 * from becoming a second identity that has to be maintained. Its own function
 * so `skill(index:)` reads the same list `skills` returns, rather than a
 * second query that could order differently.
 */
async function listSkills() {
	const rows = await db()
		.select()
		.from(documents)
		.where(eq(documents.kind, "skill"))
		.orderBy(asc(documents.path));

	return rows.map((row: typeof documents.$inferSelect, at: number) => ({
		index: at + 1,
		name: row.title ?? row.slug ?? row.path,
		description: row.summary,
		path: row.path,
		tokens: row.tokens,
		body: row.body,
	}));
}

/**
 * The shape contract, moved by hand.
 *
 * Separate from `revision` because they answer different questions: this one
 * changes when a field changes meaning, which is a client's problem, and the
 * revision changes when a file does, which is a cache's. Bumping this on every
 * edit would make it useless for the thing it is for.
 */
const API_VERSION = "1.0.0";

/*
 * Typed against the generated schema, which is itself generated from the
 * Drizzle tables. That is the whole chain closed: a column shapes a field, a
 * field shapes this, and `tsc` refuses a resolver that answers something the
 * schema never promised.
 */
export const resolvers: Resolvers = {
	Query: {
		/*
		 * A hash over every document's hash, ordered by path.
		 *
		 * Ordering matters: the same set of files has to produce the same value
		 * whatever order Postgres returns them in, or the revision would change
		 * on its own and every cache would miss forever.
		 */
		async apiVersion() {
			const rows = await db()
				.select({ sha: documents.sha, syncedAt: documents.syncedAt })
				.from(documents)
				.orderBy(asc(documents.path));

			const digest = createHash("sha256");
			for (const row of rows) digest.update(row.sha);

			const newest = rows.reduce<Date | null>(
				(latest, row) =>
					!latest || row.syncedAt > latest ? row.syncedAt : latest,
				null,
			);

			return {
				version: API_VERSION,
				revision: digest.digest("hex").slice(0, 16),
				syncedAt: newest?.toISOString() ?? null,
				documents: rows.length,
			};
		},

		/*
		 * The inverse of a cache check: hand over what you have, get back what
		 * you do not. Doing it this way round rather than "give me everything
		 * since a timestamp" means a client that missed a sync entirely still
		 * gets a correct answer, because the comparison is on content rather
		 * than on time.
		 */
		async changedSince(_, args) {
			const held = new Set(args.shas);
			const rows = await db()
				.select()
				.from(documents)
				.orderBy(asc(documents.path));

			return rows
				.filter((row: typeof documents.$inferSelect) => !held.has(row.sha))
				.map(shape);
		},

		...githubResolvers.Query,
		async totals() {
			const [row] = await db().execute<{
				documents: number;
				reference_pages: number;
				providers: number;
				synced_at: Date | null;
			}>(sql`
				select
					(select count(*)::int from ${documents}) as documents,
					(select count(*)::int from ${referencePages}) as reference_pages,
					(select count(*)::int from ${referenceProviders}) as providers,
					(select max(synced_at) from ${documents}) as synced_at
			`);

			return {
				documents: row?.documents ?? 0,
				referencePages: row?.reference_pages ?? 0,
				providers: row?.providers ?? 0,
				syncedAt: row?.synced_at ? new Date(row.synced_at).toISOString() : null,
			};
		},

		async documents(_, args) {
			const where = [
				args.kind ? eq(documents.kind, toKind(args.kind) as never) : undefined,
				args.slug ? eq(documents.slug, args.slug) : undefined,
				args.section ? eq(documents.section, args.section) : undefined,
			].filter(Boolean);

			const rows = await db()
				.select()
				.from(documents)
				.where(where.length ? and(...where) : undefined)
				.orderBy(asc(documents.path))
				.limit(Math.min(args.limit ?? 25, 200))
				.offset(args.offset ?? 0);

			return rows.map(shape);
		},

		/*
		 * The same query as `documents`, with the numbers that make truncation
		 * visible.
		 *
		 * `documents` clamps to two hundred and says nothing, which is fine for a
		 * lookup and dangerous for a count - a caller cannot tell a full page
		 * from a capped one. I acted on that once: a query for five hundred
		 * component rows returned two hundred, the tail looked absent, and a
		 * component with all five sections looked like it was missing two.
		 *
		 * Two statements rather than one with a window function. `count(*) over
		 * ()` would save a round trip and makes the row type carry a field that
		 * is not a column, which every consumer then has to know to ignore.
		 */
		async documentPage(_, args) {
			const limit = Math.min(args.limit ?? 25, 200);
			const offset = args.offset ?? 0;

			const where = [
				args.kind ? eq(documents.kind, toKind(args.kind) as never) : undefined,
				args.slug ? eq(documents.slug, args.slug) : undefined,
				args.section ? eq(documents.section, args.section) : undefined,
				args.search
					? sql`(${documents.title} ilike ${contains(args.search)}
						or ${documents.summary} ilike ${contains(args.search)}
						or ${documents.path} ilike ${contains(args.search)}
						or ${documents.body} ilike ${contains(args.search)})`
					: undefined,
			].filter(Boolean);

			const conditions = where.length ? and(...where) : undefined;

			const [rows, [counted]] = await Promise.all([
				db()
					.select()
					.from(documents)
					.where(conditions)
					.orderBy(asc(documents.path))
					.limit(limit)
					.offset(offset),
				db()
					.select({ total: sql<number>`count(*)::int` })
					.from(documents)
					.where(conditions),
			]);

			const total = counted?.total ?? 0;

			return {
				rows: rows.map(shape),
				total,
				limit,
				offset,
				hasMore: offset + rows.length < total,
			};
		},

		async document(_, args) {
			if (args.path) {
				const [row] = await db()
					.select()
					.from(documents)
					.where(eq(documents.path, args.path))
					.limit(1);
				return row ? shape(row) : null;
			}

			if (!args.slug) return null;

			/*
			 * A slug with no section means the overview. `index` first, then
			 * whatever single document the slug has - a package README has no
			 * sections at all and should still answer.
			 */
			const where = args.section
				? and(
						eq(documents.slug, args.slug),
						eq(documents.section, args.section),
					)
				: eq(documents.slug, args.slug);

			const rows = await db()
				.select()
				.from(documents)
				.where(where)
				.orderBy(asc(documents.section));

			const found =
				rows.find(
					(row: typeof documents.$inferSelect) =>
						row.section === (args.section ?? "index"),
				) ?? rows[0];

			return found ? shape(found) : null;
		},

		async search(_, args) {
			const pattern = contains(args.query);
			const where = [
				sql`(${documents.title} ilike ${pattern} or ${documents.summary} ilike ${pattern} or ${documents.body} ilike ${pattern})`,
				args.kind ? eq(documents.kind, toKind(args.kind) as never) : undefined,
			].filter(Boolean);

			const rows = await db()
				.select()
				.from(documents)
				.where(and(...where))
				// Smallest first: a match in a two-hundred-token API section is a
				// better answer than the same match somewhere in a source file.
				.orderBy(asc(documents.tokens))
				.limit(Math.min(args.limit ?? 20, 100));

			const needle = args.query.toLowerCase();
			return rows.map((row: typeof documents.$inferSelect) => ({
				document: shape(row),
				excerpt:
					row.body
						.split("\n")
						.find((line: string) => line.toLowerCase().includes(needle))
						?.trim()
						.slice(0, 200) ?? "",
			}));
		},

		/*
		 * Skills, as a view over the documents whose kind is `skill`.
		 *
		 * Ordered by name and numbered from one on the way out, so the index is a
		 * property of the list rather than something stored - which is what keeps
		 * it from being a second identity that has to be maintained.
		 */
		skills: listSkills,

		async skill(_, args) {
			const all = await listSkills();
			if (args.name) {
				return (
					all.find((one) => one.name === args.name) ??
					all.find((one) => one.path.includes(args.name as string)) ??
					null
				);
			}
			return args.index ? (all[args.index - 1] ?? null) : null;
		},

		/*
		 * Collections: saved queries over the documents index.
		 *
		 * Flattened here rather than resolved field by field, because the shape
		 * the server returns - a definition, a count and a page of members - is
		 * already one round trip, and a `members` resolver would run the filter a
		 * second time to answer a field the first query had in hand.
		 */
		async collections() {
			const all = await getCollections();
			return all.map((one) => ({
				...one.collection,
				kind: one.collection.kind ? fromKind(one.collection.kind) : null,
				total: one.total,
				tokens: one.tokens,
				// Deliberately empty in the listing. Every collection's members is
				// every collection's filter run, which for a page that only shows
				// sizes is several hundred rows nobody asked for.
				members: [],
			}));
		},

		async collection(_, args) {
			const found = await getCollection(args.id);
			if (!found) return null;

			return {
				...found.collection,
				kind: found.collection.kind ? fromKind(found.collection.kind) : null,
				total: found.total,
				tokens: found.tokens,
				members: found.members.map((member) => ({
					...member,
					// The catalogue types this loosely; the column does not.
					kind: fromKind(member.kind as DocumentKind),
				})),
			};
		},

		/*
		 * Sharding, computed rather than read from the manifest.
		 *
		 * `packages/cli/references/index.json` records the same thing and is not
		 * the answer to use here: it describes the shards as they were *written*,
		 * and this graph serves the rows as they were *synced*. Reading the
		 * manifest would report a shard count for a provider whose entries never
		 * made it into the database, which is the one disagreement worth being
		 * unable to have.
		 *
		 * The rule is reimplemented in one line - `ceil(entries / limit)` per
		 * section - and the limit is stated in the schema beside it. Three things
		 * implement this rule; that they agree is checked by the numbers matching,
		 * not by them sharing code, because the writer runs in the CLI and cannot
		 * be imported here.
		 */
		/*
		 * Elements: the library as a graph rather than a list.
		 *
		 * `parts` and `partOf` are field resolvers rather than being expanded
		 * here, and that is not an optimisation - it is the only thing that
		 * terminates. A block's parts have parts: `folder-shelf` includes
		 * `context-menu`, which includes `icon`. Expanding eagerly would recurse
		 * until the stack ran out, and a depth limit would be an arbitrary
		 * number deciding what a client is allowed to ask.
		 *
		 * Resolved per field, the client's query decides the depth, which is what
		 * GraphQL is for.
		 */
		async elements(_, args) {
			return getElements(args);
		},

		async element(_, args) {
			return getElement(args.name);
		},

		async elementShard(_, args) {
			return getElementShard(args.path);
		},

		async sharding() {
			const SHARD_LIMIT = 500;

			const rows = await db().execute<{
				provider: string;
				title: string | null;
				source: string;
				used_for: string | null;
				sections: number;
				shards: number;
				entries: number;
			}>(sql`
				select
					p.provider,
					p.title,
					p.source,
					p.used_for,
					count(*)::int as sections,
					sum(ceil(s.entries::numeric / ${SHARD_LIMIT}))::int as shards,
					sum(s.entries)::int as entries
				from ${referenceProviders} p
				join (
					select provider, section, count(*)::int as entries
					from ${referencePages}
					group by provider, section
				) s on s.provider = p.provider
				group by p.provider, p.title, p.source, p.used_for
				order by sum(s.entries) desc
			`);

			const byProvider = [...rows].map((row) => ({
				provider: row.provider,
				title: row.title,
				source: row.source,
				usedFor: row.used_for,
				sections: row.sections,
				shards: row.shards,
				entries: row.entries,
			}));

			return {
				limit: SHARD_LIMIT,
				providers: byProvider.length,
				shards: byProvider.reduce((sum, one) => sum + one.shards, 0),
				entries: byProvider.reduce((sum, one) => sum + one.entries, 0),
				byProvider,
			};
		},

		async providers() {
			return db()
				.select()
				.from(referenceProviders)
				.orderBy(desc(referenceProviders.entries));
		},
		async findReference(_, args) {
			const pattern = contains(args.query);
			const where = [
				sql`(${referencePages.name} ilike ${pattern} or ${referencePages.description} ilike ${pattern} or ${referencePages.section} ilike ${pattern})`,
				args.provider ? eq(referencePages.provider, args.provider) : undefined,
				args.section ? eq(referencePages.section, args.section) : undefined,
			].filter(Boolean);

			return db()
				.select()
				.from(referencePages)
				.where(and(...where))
				.orderBy(asc(referencePages.name))
				.limit(Math.min(args.limit ?? 20, 100));
		},
	},

	Repository: githubResolvers.Repository,

	/*
	 * The two edges of the element graph, resolved on demand.
	 *
	 * Each looks its neighbours up by name rather than holding them, so a cycle
	 * in the registry would produce a query that gets deeper rather than a
	 * server that never returns - the client's selection set is the bound.
	 */
	Element: {
		async parts(parent) {
			const found = await Promise.all(
				parent.partNames.map((name) => getElement(name)),
			);

			/*
			 * A predicate rather than `filter(Boolean)`.
			 *
			 * `Boolean` is not a type guard, so the result stayed
			 * `(Element | null)[]` while the schema promises `[Element!]!`. The
			 * runtime was already dropping the nulls; nothing could prove it,
			 * and the first thing a reader does with an unprovable claim is
			 * cast it away.
			 */
			return found.filter((one) => one !== null);
		},

		async partOf(parent) {
			const found = await Promise.all(
				parent.partOfNames.map((name) => getElement(name)),
			);
			return found.filter((one) => one !== null);
		},
	},

	ReferenceProvider: {
		async pages(parent, args) {
			const where = [
				eq(referencePages.provider, parent.provider),
				args.section ? eq(referencePages.section, args.section) : undefined,
			].filter(Boolean);

			return db()
				.select()
				.from(referencePages)
				.where(and(...where))
				.orderBy(asc(referencePages.name))
				.limit(Math.min(args.limit ?? 25, 200));
		},
	},
};
