#!/usr/bin/env node
/*
 * Generate the schema.org vocabulary this repo types its elements with.
 *
 * The vocabulary is a published artefact - one JSON-LD file, versioned, at
 * schema.org - so the honest thing is to read it rather than to hand-write a
 * subset and let it rot. A thousand classes is not something anybody maintains
 * by hand, and a hand-picked subset is exactly the thing that will not have the
 * type the next element needs.
 *
 *   node scripts/schema-org.mjs          # regenerate from the published file
 *   node scripts/schema-org.mjs --check  # fail if the output is not current
 *
 * The source is downloaded rather than committed: it is 1.5 MB of JSON-LD that
 * nothing reads at runtime, and the generated module is the part that matters.
 *
 * What comes out is deliberately three things and no more:
 *
 *   SCHEMA_TYPES      every class name, so a type can be validated
 *   SCHEMA_PARENTS    rdfs:subClassOf, so `isSchemaType(x, "CreativeWork")`
 *                     can answer for a subtype it has never heard of
 *   SCHEMA_PROPERTIES each class's own properties, from schema:domainIncludes
 *
 * Inherited properties are derived at runtime from the parent chain rather than
 * flattened here, because flattening multiplies the file by the depth of the
 * tree to save a loop nobody is running in anger.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { argv } from "node:process";

const SOURCE =
	"https://schema.org/version/latest/schemaorg-current-https.jsonld";
const OUT = new URL(
	"../packages/db/src/schema-org.generated.ts",
	import.meta.url,
);

/** `schema:VideoObject` -> `VideoObject`. Anything else is another vocabulary. */
function localName(id) {
	if (typeof id !== "string") return null;
	if (!id.startsWith("schema:")) return null;
	return id.slice("schema:".length);
}

function asArray(value) {
	if (value === undefined || value === null) return [];
	return Array.isArray(value) ? value : [value];
}

function ids(value) {
	return asArray(value)
		.map((entry) => localName(entry?.["@id"]))
		.filter((name) => name !== null);
}

async function vocabulary() {
	const response = await fetch(SOURCE);
	if (!response.ok) {
		throw new Error(`schema.org returned ${response.status} for ${SOURCE}`);
	}
	return await response.json();
}

function build(graph) {
	const types = [];
	const parents = {};
	const properties = {};

	for (const node of graph) {
		const kinds = asArray(node["@type"]);
		const name = localName(node["@id"]);
		if (!name) continue;

		/*
		 * `schema:DataType` and its members (Text, Number, Date) are classes in
		 * the file but they are value shapes, not things anything can be. They
		 * are kept out so `SchemaTypeName` means "something that can be a
		 * subject", which is what every use of it here wants.
		 */
		if (kinds.includes("rdfs:Class")) {
			const supers = ids(node["rdfs:subClassOf"]);
			if (name === "DataType" || supers.includes("DataType")) continue;

			types.push(name);
			if (supers.length > 0) parents[name] = supers;
			continue;
		}

		if (kinds.includes("rdf:Property")) {
			for (const domain of ids(node["schema:domainIncludes"])) {
				properties[domain] ??= [];
				properties[domain].push(name);
			}
		}
	}

	types.sort();
	for (const list of Object.values(properties)) list.sort();

	return { types, parents, properties };
}

/** Sorted keys, so a regenerated file diffs only where the vocabulary moved. */
function record(map) {
	const lines = Object.keys(map)
		.sort()
		.map((key) => `\t${JSON.stringify(key)}: ${JSON.stringify(map[key])},`);
	return `{\n${lines.join("\n")}\n}`;
}

function render({ types, parents, properties }) {
	return `// Generated by scripts/schema-org.mjs from ${SOURCE}
// Do not edit by hand. Run \`pnpm run schema-org\` to refresh.

/*
 * The schema.org vocabulary, as data.
 *
 * ${types.length} classes and the properties each one declares. This is the
 * type system the elements of this site describe themselves in: a registry
 * entry names one of these, and the row that stores an element is validated
 * and serialised against it.
 */

export const SCHEMA_TYPES = ${JSON.stringify(types)} as const;

/** Every class schema.org publishes, as a union. */
export type SchemaTypeName = (typeof SCHEMA_TYPES)[number];

/** \`rdfs:subClassOf\`. One entry per class that has a parent. */
export const SCHEMA_PARENTS: Readonly<Record<string, readonly string[]>> = ${record(parents)};

/** \`schema:domainIncludes\`: the properties a class declares itself. */
export const SCHEMA_PROPERTIES: Readonly<Record<string, readonly string[]>> = ${record(properties)};
`;
}

const graph = (await vocabulary())["@graph"];
const next = render(build(graph));

const digest = (text) => createHash("sha256").update(text).digest("hex");

if (argv.includes("--check")) {
	const current = readFileSync(OUT, "utf8");
	if (digest(current) !== digest(next)) {
		console.error(
			"schema-org.generated.ts is behind schema.org. Run: pnpm run schema-org",
		);
		process.exit(1);
	}
	console.log("schema.org vocabulary is current.");
} else {
	writeFileSync(OUT, next);
	const { types } = build(graph);
	console.log(
		`Wrote ${types.length} classes to packages/db/src/schema-org.generated.ts`,
	);
}
